[package]
name = "macros"
version = "0.1.0"
edition = "2024"
[lib]
proc-macro = true
[dependencies]
syn = "2.0.100"
quote = "1.0.40"
tokio = { version = "1.44.0",default-features = false, features = ["full"] }